### ISSUE TITLE
Code is not indented as go code should be (go fmt)

### ISSUE THREAD

**Issue by Soulou** [alfredxing/calc#2]
Please execute `go fmt ./...` at the root of the project to correctly indent the source code of the project. It would be great to make it a more go-ish code.

**Comment by alfredxing** [comment]
Thanks for the tip! The large indents are not too much to my liking though. I'll open this one up to discussion.

**Comment by FiloSottile** [comment]
Hey, I hate to be that guy on the internet, but yes, the Go community really cares about `go fmt` - also to avoid discussions like this.

It's not anyone's favorite style but it's everyone's adopted style.

---

Ah! BTW, `go fmt` indents are tabs, so you decide how wide to see them in your editor.

**Comment by alfredxing** [comment]
@FiloSottile Thanks for the input (I'm definitely new to the Go community)! `git diff` displayed them as spaces, but my editor seemed to behave a bit better.
