### ISSUE TITLE
Can't quit with ctrl+c

### ISSUE THREAD

**Issue by betrisey** [alfredxing/calc#6]
When I quit the program with ctrl+c, I can't type in the terminal anymore.
I have this issue with OS X.

**Comment by ericdorsey** [comment]
@betrisey 
Can you clarify if you can't type, or if it's just that nothing is echo'd from the cursor? In other words, try typing a command and hitting enter anyway, just to see what happens?

Does ```stty echo``` restore cursor echo? I [found this on SuperUser](http://superuser.com/questions/283927/is-the-invisible-text-bug-in-bash-a-bug-or-a-feature) on seeing your post, and ```stty echo``` worked for me, so maybe it's something about the way the CTRL+C is processed by Calc?

OSX here as well. For me, when I CTRL-C out of Calc, I can still type, it's just that nothing is shown (no echo) -- in other words, if I type ```ls``` and hit enter, I still get a list of files. It's probably also worth noting that when typing:

```
> exit
```
Calc exits without issue for me.

**Comment by betrisey** [comment]
@ericdorsey
It's just that nothing is echo'd from the cursor. All commands works and I stty echo restore cursor echo.
Thank you.

**Comment by ericdorsey** [comment]
@betrisey 
You're welcome. I still think this is a bug though personally, I would think CTRL-C would leave echo on in the terminal.

**Comment by alfredxing** [comment]
Definitely is a bug, I'll look into it.

**Comment by alfredxing** [comment]
@betrisey @ericdorsey Can you `go get -u` again and test this one out?

**Comment by ericdorsey** [comment]
Updated w/ ```go get -u``` and issue resolved.

**Comment by alfredxing** [comment]
Awesome, thanks for confirming!
